### ISSUE TITLE
Wesbite is down FYI

### ISSUE THREAD

**Issue by yosufali** [builtwithdjango/builtwithdjango#58]
Just wanted to let you know the site is not reachable, but wasn't sure best way to do so.

Oddly: 
https://builtwithdjango.com/projects/new/ - loads okay intermittently
https://builtwithdjango.com/projects/ - produces 500
https://builtwithdjango.com/ - does not connect

**Comment by rasulkireev** [comment]
Thank you.

I have started to have a problem with my server a few hours ago. working on it right now. Will update ASAP

**Comment by rasulkireev** [comment]
Should be back up 👍
